name: Deploy
on: 
  workflow_dispatch:

  # issues:
  #   types: [opened]

jobs:
  jobone:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Output
        shell: pwsh
        run: Write-Host "Step One"
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ vars.$RESOURCE_GROUP_NAME }}
          template: ./InfrastructureAsCode/main.bicep
          # parameters: examples/template/parameters.json storageAccountType=Standard_LRS sqlServerPassword=${{ secrets.SQL_SERVER }}
          # additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
          
      
  
