name: Test PowerShell
on: workflow_dispatch

jobs:
  jobone:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Output
        shell: pwsh
        run: Write-Host "Step One"
#      - name: Azure Login
#        uses: Azure/login@v1.4.6
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - run: |
#          az account show
  jobtwo:
    name: job2
    needs: jobone
    runs-on: ubuntu-latest
    steps:
      - name: CowSays Moo
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'ship ship ship!'
          color: 'red'
#      - name: Azure Login
#        uses: Azure/login@v1.4.6
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - run: |
#          az account show